[package]
name = "memory_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.29"
log = "0.4"
log4rs = "1.2"
crossterm = "0.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"